wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1645841778
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 13
      - 16
      4: 3.7.12
      5: 0.12.10
      8:
      - 5
batch_size:
  desc: null
  value: 16
epoch:
  desc: null
  value: 5000
lr_rate:
  desc: null
  value: 0.0001
